#!/usr/bin/env bash

echo "Running pre-commit hook with lint checks."

pids=""

npm run clean > /dev/null &
pids="$pids $!"

get_changed_files()
{
    git diff --staged --name-only --diff-filter=d -- "$@"
}

# Get changed CSS files
changed_css=$(get_changed_files 'css/*.css')
if [ ! -z "$changed_css" ]; then
    # Convert newlines to array for stylelint
    stylelint $changed_css --config configs/.stylelintrc.json --ignore-path configs/.stylelintignore &
    pids="$pids $!"
fi

# Get changed JS files  
changed_js=$(get_changed_files '*.cjs' '*.js' '*.mjs')
if [ ! -z "$changed_js" ]; then
    eslint $changed_js --config configs/eslint.config.mjs &
    pids="$pids $!"
fi

# Get changed docs files
changed_docs=$(get_changed_files 'locales/*/*.json' 'docs/*.md' 'docs/translated_readmes/*.md' '*.md')
if [ ! -z "$changed_docs" ]; then
    prettier -c $changed_docs --config configs/.prettierrc.json --ignore-path .gitignore --ignore-path configs/.prettierignore &
    pids="$pids $!"
fi

RESULT=0
wait $pids || let "RESULT=1"

if [ "$RESULT" == "1" ]; then
    echo "One of the linters has identified formatting issues. Run 'npm run lint-fix' before committing."
    exit 1
fi
